/**
 * FHIR Resource Validator
 * Uses @babelfhir-ts/client-r4 to validate incoming FHIR R4 resources against
 * their base resource schemas and FHIRPath constraints.
 *
 * When a US Core Implementation Guide is installed (babelfhir-ts install
 * hl7.fhir.us.core@8.0.0), profile-aware validation is automatically available.
 */

import { FhirR4Client } from "@babelfhir-ts/client-r4";

/** Result returned by the validator. */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  resourceType: string;
  resourceId?: string;
}

/** Thin wrapper around the BabelFHIR-TS R4 client for CMMC use. */
export class FhirValidator {
  private readonly client: FhirR4Client;

  constructor(fhirBaseUrl?: string) {
    this.client = new FhirR4Client(
      fhirBaseUrl ?? "http://localhost:8080/fhir"
    );
  }

  /**
   * Validate a raw FHIR resource object.
   *
   * - Checks that `resourceType` is present and recognised.
   * - Runs any FHIRPath-based constraints registered for the type.
   * - Returns errors and warnings without throwing.
   */
  async validate(resource: Record<string, unknown>): Promise<ValidationResult> {
    const resourceType = resource["resourceType"] as string | undefined;
    const resourceId = resource["id"] as string | undefined;

    const errors: string[] = [];
    const warnings: string[] = [];

    if (!resourceType) {
      return {
        valid: false,
        errors: ["'resourceType' field is required."],
        warnings,
        resourceType: "Unknown",
        resourceId,
      };
    }

    // Attempt profile-aware validation if the resource type is supported.
    try {
      // The typed accessor (e.g., client.auditEvent()) returns a typed helper
      // that exposes a validate() method generated by BabelFHIR-TS.
      const accessor = this._getTypedAccessor(resourceType);
      if (accessor && typeof accessor.validate === "function") {
        const result = await accessor.validate(resource as fhir4.Resource);
        for (const e of result.errors ?? []) {
          errors.push(typeof e === "string" ? e : JSON.stringify(e));
        }
        for (const w of result.warnings ?? []) {
          warnings.push(typeof w === "string" ? w : JSON.stringify(w));
        }
      } else {
        // Type not yet generated — perform basic structural check.
        this._basicStructureCheck(resource, warnings);
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      warnings.push(`Validation skipped: ${msg}`);
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
      resourceType,
      resourceId,
    };
  }

  /** Map a FHIR resource type string to the corresponding client method. */
  private _getTypedAccessor(resourceType: string): unknown {
    const methodName =
      resourceType.charAt(0).toLowerCase() + resourceType.slice(1);
    const clientAsRecord = this.client as Record<string, unknown>;
    return typeof clientAsRecord[methodName] === "function"
      ? clientAsRecord[methodName]
      : undefined;
  }

  /** Lightweight structural checks for unsupported resource types. */
  private _basicStructureCheck(
    resource: Record<string, unknown>,
    warnings: string[]
  ): void {
    if (!resource["id"]) {
      warnings.push("Resource is missing 'id' — may complicate traceability.");
    }
    if (!resource["meta"]) {
      warnings.push(
        "Resource is missing 'meta' — version tracking recommended."
      );
    }
  }
}
